//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 12:14:36 AM CST 
//


package org.oasis.xmile.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="eqn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mathml" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="units" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="doc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}gf" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}dimensions" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}event_poster" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}scale" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}range" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}format" minOccurs="0"/>
 *         &lt;element name="multiplier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="non_negative" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}boolean_or_empty_type" minOccurs="0"/>
 *         &lt;element name="overflow" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type"/>
 *         &lt;element name="leak" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type"/>
 *         &lt;element name="leak_integers" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type"/>
 *         &lt;element name="element" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="eqn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="mathml" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}gf" minOccurs="0"/>
 *                   &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}event_poster" minOccurs="0"/>
 *                   &lt;element name="multiplier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="non_negative" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}boolean_or_empty_type" minOccurs="0"/>
 *                   &lt;element name="overflow" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type"/>
 *                   &lt;element name="leak" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type"/>
 *                   &lt;element name="leak_integers" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type"/>
 *                 &lt;/choice>
 *                 &lt;attribute name="subscript" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="access" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}access_type" />
 *       &lt;attribute name="autoexport" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="subscript" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="leak_start" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *       &lt;attribute name="leak_end" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eqnOrMathmlOrUnits"
})
@XmlRootElement(name = "flow")
public class Flow {

    @XmlElementRefs({
        @XmlElementRef(name = "eqn", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "leak_integers", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "doc", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "multiplier", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "units", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "leak", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "non_negative", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "format", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = Format.class, required = false),
        @XmlElementRef(name = "gf", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = Gf.class, required = false),
        @XmlElementRef(name = "event_poster", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = EventPoster.class, required = false),
        @XmlElementRef(name = "dimensions", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = Dimensions.class, required = false),
        @XmlElementRef(name = "range", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = Range.class, required = false),
        @XmlElementRef(name = "overflow", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scale", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = Scale.class, required = false),
        @XmlElementRef(name = "element", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "mathml", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false)
    })
    protected List<Object> eqnOrMathmlOrUnits;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "access")
    protected AccessType access;
    @XmlAttribute(name = "autoexport")
    protected Boolean autoexport;
    @XmlAttribute(name = "subscript")
    protected String subscript;
    @XmlAttribute(name = "leak_start")
    protected Double leakStart;
    @XmlAttribute(name = "leak_end")
    protected Double leakEnd;

    /**
     * Gets the value of the eqnOrMathmlOrUnits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eqnOrMathmlOrUnits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEqnOrMathmlOrUnits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link EmptyType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link EmptyType }{@code >}
     * {@link JAXBElement }{@code <}{@link BooleanOrEmptyType }{@code >}
     * {@link Format }
     * {@link Gf }
     * {@link EventPoster }
     * {@link Dimensions }
     * {@link Range }
     * {@link JAXBElement }{@code <}{@link EmptyType }{@code >}
     * {@link Scale }
     * {@link JAXBElement }{@code <}{@link Flow.Element }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getEqnOrMathmlOrUnits() {
        if (eqnOrMathmlOrUnits == null) {
            eqnOrMathmlOrUnits = new ArrayList<Object>();
        }
        return this.eqnOrMathmlOrUnits;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the access property.
     * 
     * @return
     *     possible object is
     *     {@link AccessType }
     *     
     */
    public AccessType getAccess() {
        return access;
    }

    /**
     * Sets the value of the access property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessType }
     *     
     */
    public void setAccess(AccessType value) {
        this.access = value;
    }

    /**
     * Gets the value of the autoexport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAutoexport() {
        if (autoexport == null) {
            return false;
        } else {
            return autoexport;
        }
    }

    /**
     * Sets the value of the autoexport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoexport(Boolean value) {
        this.autoexport = value;
    }

    /**
     * Gets the value of the subscript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscript() {
        return subscript;
    }

    /**
     * Sets the value of the subscript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscript(String value) {
        this.subscript = value;
    }

    /**
     * Gets the value of the leakStart property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getLeakStart() {
        if (leakStart == null) {
            return  0.0D;
        } else {
            return leakStart;
        }
    }

    /**
     * Sets the value of the leakStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLeakStart(Double value) {
        this.leakStart = value;
    }

    /**
     * Gets the value of the leakEnd property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getLeakEnd() {
        if (leakEnd == null) {
            return  1.0D;
        } else {
            return leakEnd;
        }
    }

    /**
     * Sets the value of the leakEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLeakEnd(Double value) {
        this.leakEnd = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="eqn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="mathml" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}gf" minOccurs="0"/>
     *         &lt;element ref="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}event_poster" minOccurs="0"/>
     *         &lt;element name="multiplier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="non_negative" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}boolean_or_empty_type" minOccurs="0"/>
     *         &lt;element name="overflow" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type"/>
     *         &lt;element name="leak" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type"/>
     *         &lt;element name="leak_integers" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type"/>
     *       &lt;/choice>
     *       &lt;attribute name="subscript" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eqnOrMathmlOrGf"
    })
    public static class Element {

        @XmlElementRefs({
            @XmlElementRef(name = "leak_integers", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "mathml", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "non_negative", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "event_poster", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = EventPoster.class, required = false),
            @XmlElementRef(name = "gf", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = Gf.class, required = false),
            @XmlElementRef(name = "eqn", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "overflow", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "leak", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "multiplier", namespace = "http://docs.oasis-open.org/xmile/ns/XMILE/v1.0", type = JAXBElement.class, required = false)
        })
        protected List<Object> eqnOrMathmlOrGf;
        @XmlAttribute(name = "subscript", required = true)
        protected String subscript;

        /**
         * Gets the value of the eqnOrMathmlOrGf property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the eqnOrMathmlOrGf property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEqnOrMathmlOrGf().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link EmptyType }{@code >}
         * {@link JAXBElement }{@code <}{@link BooleanOrEmptyType }{@code >}
         * {@link Gf }
         * {@link EventPoster }
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link EmptyType }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link EmptyType }{@code >}
         * 
         * 
         */
        public List<Object> getEqnOrMathmlOrGf() {
            if (eqnOrMathmlOrGf == null) {
                eqnOrMathmlOrGf = new ArrayList<Object>();
            }
            return this.eqnOrMathmlOrGf;
        }

        /**
         * Gets the value of the subscript property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubscript() {
            return subscript;
        }

        /**
         * Sets the value of the subscript property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubscript(String value) {
            this.subscript = value;
        }

    }

}
