//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 12:14:36 AM CST 
//


package org.oasis.xmile.v1_0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="uses_conveyor" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="arrest" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="leak" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="uses_queue" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="overflow" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="uses_submodels" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type" minOccurs="0"/>
 *         &lt;element name="uses_macros" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="references_macros" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="option_filters" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="uses_event_posters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="messages" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="has_model_view" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type" minOccurs="0"/>
 *         &lt;element name="uses_outputs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="numeric_display" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="lamp" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="gauge" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="uses_inputs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="numeric_input" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="graphical_input" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="uses_annotation" type="{http://docs.oasis-open.org/xmile/ns/XMILE/v1.0}empty_type" minOccurs="0"/>
 *         &lt;element name="uses_arrays" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="max_dimensions" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="invalid_index_value" default="0">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *                       &lt;enumeration value="0"/>
 *                       &lt;enumeration value="NaN"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="namespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "options")
public class Options {

    @XmlElement(name = "uses_conveyor")
    protected Options.UsesConveyor usesConveyor;
    @XmlElement(name = "uses_queue")
    protected Options.UsesQueue usesQueue;
    @XmlElement(name = "uses_submodels")
    protected EmptyType usesSubmodels;
    @XmlElement(name = "uses_macros")
    protected Options.UsesMacros usesMacros;
    @XmlElement(name = "uses_event_posters")
    protected Options.UsesEventPosters usesEventPosters;
    @XmlElement(name = "has_model_view")
    protected EmptyType hasModelView;
    @XmlElement(name = "uses_outputs")
    protected Options.UsesOutputs usesOutputs;
    @XmlElement(name = "uses_inputs")
    protected Options.UsesInputs usesInputs;
    @XmlElement(name = "uses_annotation")
    protected EmptyType usesAnnotation;
    @XmlElement(name = "uses_arrays")
    protected Options.UsesArrays usesArrays;
    @XmlAttribute(name = "namespace")
    protected String namespace;

    /**
     * Gets the value of the usesConveyor property.
     * 
     * @return
     *     possible object is
     *     {@link Options.UsesConveyor }
     *     
     */
    public Options.UsesConveyor getUsesConveyor() {
        return usesConveyor;
    }

    /**
     * Sets the value of the usesConveyor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options.UsesConveyor }
     *     
     */
    public void setUsesConveyor(Options.UsesConveyor value) {
        this.usesConveyor = value;
    }

    /**
     * Gets the value of the usesQueue property.
     * 
     * @return
     *     possible object is
     *     {@link Options.UsesQueue }
     *     
     */
    public Options.UsesQueue getUsesQueue() {
        return usesQueue;
    }

    /**
     * Sets the value of the usesQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options.UsesQueue }
     *     
     */
    public void setUsesQueue(Options.UsesQueue value) {
        this.usesQueue = value;
    }

    /**
     * Gets the value of the usesSubmodels property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyType }
     *     
     */
    public EmptyType getUsesSubmodels() {
        return usesSubmodels;
    }

    /**
     * Sets the value of the usesSubmodels property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyType }
     *     
     */
    public void setUsesSubmodels(EmptyType value) {
        this.usesSubmodels = value;
    }

    /**
     * Gets the value of the usesMacros property.
     * 
     * @return
     *     possible object is
     *     {@link Options.UsesMacros }
     *     
     */
    public Options.UsesMacros getUsesMacros() {
        return usesMacros;
    }

    /**
     * Sets the value of the usesMacros property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options.UsesMacros }
     *     
     */
    public void setUsesMacros(Options.UsesMacros value) {
        this.usesMacros = value;
    }

    /**
     * Gets the value of the usesEventPosters property.
     * 
     * @return
     *     possible object is
     *     {@link Options.UsesEventPosters }
     *     
     */
    public Options.UsesEventPosters getUsesEventPosters() {
        return usesEventPosters;
    }

    /**
     * Sets the value of the usesEventPosters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options.UsesEventPosters }
     *     
     */
    public void setUsesEventPosters(Options.UsesEventPosters value) {
        this.usesEventPosters = value;
    }

    /**
     * Gets the value of the hasModelView property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyType }
     *     
     */
    public EmptyType getHasModelView() {
        return hasModelView;
    }

    /**
     * Sets the value of the hasModelView property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyType }
     *     
     */
    public void setHasModelView(EmptyType value) {
        this.hasModelView = value;
    }

    /**
     * Gets the value of the usesOutputs property.
     * 
     * @return
     *     possible object is
     *     {@link Options.UsesOutputs }
     *     
     */
    public Options.UsesOutputs getUsesOutputs() {
        return usesOutputs;
    }

    /**
     * Sets the value of the usesOutputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options.UsesOutputs }
     *     
     */
    public void setUsesOutputs(Options.UsesOutputs value) {
        this.usesOutputs = value;
    }

    /**
     * Gets the value of the usesInputs property.
     * 
     * @return
     *     possible object is
     *     {@link Options.UsesInputs }
     *     
     */
    public Options.UsesInputs getUsesInputs() {
        return usesInputs;
    }

    /**
     * Sets the value of the usesInputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options.UsesInputs }
     *     
     */
    public void setUsesInputs(Options.UsesInputs value) {
        this.usesInputs = value;
    }

    /**
     * Gets the value of the usesAnnotation property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyType }
     *     
     */
    public EmptyType getUsesAnnotation() {
        return usesAnnotation;
    }

    /**
     * Sets the value of the usesAnnotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyType }
     *     
     */
    public void setUsesAnnotation(EmptyType value) {
        this.usesAnnotation = value;
    }

    /**
     * Gets the value of the usesArrays property.
     * 
     * @return
     *     possible object is
     *     {@link Options.UsesArrays }
     *     
     */
    public Options.UsesArrays getUsesArrays() {
        return usesArrays;
    }

    /**
     * Sets the value of the usesArrays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options.UsesArrays }
     *     
     */
    public void setUsesArrays(Options.UsesArrays value) {
        this.usesArrays = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="max_dimensions" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="invalid_index_value" default="0">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
     *             &lt;enumeration value="0"/>
     *             &lt;enumeration value="NaN"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsesArrays {

        @XmlAttribute(name = "max_dimensions", required = true)
        protected BigInteger maxDimensions;
        @XmlAttribute(name = "invalid_index_value")
        protected Double invalidIndexValue;

        /**
         * Gets the value of the maxDimensions property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMaxDimensions() {
            return maxDimensions;
        }

        /**
         * Sets the value of the maxDimensions property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMaxDimensions(BigInteger value) {
            this.maxDimensions = value;
        }

        /**
         * Gets the value of the invalidIndexValue property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public double getInvalidIndexValue() {
            if (invalidIndexValue == null) {
                return  0.0D;
            } else {
                return invalidIndexValue;
            }
        }

        /**
         * Sets the value of the invalidIndexValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setInvalidIndexValue(Double value) {
            this.invalidIndexValue = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="arrest" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="leak" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsesConveyor {

        @XmlAttribute(name = "arrest")
        protected Boolean arrest;
        @XmlAttribute(name = "leak")
        protected Boolean leak;

        /**
         * Gets the value of the arrest property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isArrest() {
            return arrest;
        }

        /**
         * Sets the value of the arrest property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setArrest(Boolean value) {
            this.arrest = value;
        }

        /**
         * Gets the value of the leak property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLeak() {
            return leak;
        }

        /**
         * Sets the value of the leak property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLeak(Boolean value) {
            this.leak = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="messages" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsesEventPosters {

        @XmlAttribute(name = "messages")
        protected Boolean messages;

        /**
         * Gets the value of the messages property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMessages() {
            return messages;
        }

        /**
         * Sets the value of the messages property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMessages(Boolean value) {
            this.messages = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="numeric_input" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="list" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="graphical_input" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsesInputs {

        @XmlAttribute(name = "numeric_input")
        protected Boolean numericInput;
        @XmlAttribute(name = "list")
        protected Boolean list;
        @XmlAttribute(name = "graphical_input")
        protected Boolean graphicalInput;

        /**
         * Gets the value of the numericInput property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isNumericInput() {
            return numericInput;
        }

        /**
         * Sets the value of the numericInput property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setNumericInput(Boolean value) {
            this.numericInput = value;
        }

        /**
         * Gets the value of the list property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setList(Boolean value) {
            this.list = value;
        }

        /**
         * Gets the value of the graphicalInput property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isGraphicalInput() {
            return graphicalInput;
        }

        /**
         * Sets the value of the graphicalInput property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setGraphicalInput(Boolean value) {
            this.graphicalInput = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="references_macros" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="option_filters" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsesMacros {

        @XmlAttribute(name = "references_macros", required = true)
        protected boolean referencesMacros;
        @XmlAttribute(name = "option_filters", required = true)
        protected boolean optionFilters;

        /**
         * Gets the value of the referencesMacros property.
         * 
         */
        public boolean isReferencesMacros() {
            return referencesMacros;
        }

        /**
         * Sets the value of the referencesMacros property.
         * 
         */
        public void setReferencesMacros(boolean value) {
            this.referencesMacros = value;
        }

        /**
         * Gets the value of the optionFilters property.
         * 
         */
        public boolean isOptionFilters() {
            return optionFilters;
        }

        /**
         * Sets the value of the optionFilters property.
         * 
         */
        public void setOptionFilters(boolean value) {
            this.optionFilters = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="numeric_display" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="lamp" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="gauge" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsesOutputs {

        @XmlAttribute(name = "numeric_display")
        protected Boolean numericDisplay;
        @XmlAttribute(name = "lamp")
        protected Boolean lamp;
        @XmlAttribute(name = "gauge")
        protected Boolean gauge;

        /**
         * Gets the value of the numericDisplay property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isNumericDisplay() {
            return numericDisplay;
        }

        /**
         * Sets the value of the numericDisplay property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setNumericDisplay(Boolean value) {
            this.numericDisplay = value;
        }

        /**
         * Gets the value of the lamp property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLamp() {
            return lamp;
        }

        /**
         * Sets the value of the lamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLamp(Boolean value) {
            this.lamp = value;
        }

        /**
         * Gets the value of the gauge property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isGauge() {
            return gauge;
        }

        /**
         * Sets the value of the gauge property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setGauge(Boolean value) {
            this.gauge = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="overflow" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UsesQueue {

        @XmlAttribute(name = "overflow")
        protected Boolean overflow;

        /**
         * Gets the value of the overflow property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isOverflow() {
            return overflow;
        }

        /**
         * Sets the value of the overflow property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOverflow(Boolean value) {
            this.overflow = value;
        }

    }

}
