//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 12:14:36 AM CST 
//


package org.oasis.xmile.v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for standard_color_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="standard_color_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="aqua"/>
 *     &lt;enumeration value="black"/>
 *     &lt;enumeration value="blue"/>
 *     &lt;enumeration value="fuchsia"/>
 *     &lt;enumeration value="gray"/>
 *     &lt;enumeration value="green"/>
 *     &lt;enumeration value="lime"/>
 *     &lt;enumeration value="maroon"/>
 *     &lt;enumeration value="navy"/>
 *     &lt;enumeration value="olive"/>
 *     &lt;enumeration value="purple"/>
 *     &lt;enumeration value="red"/>
 *     &lt;enumeration value="silver"/>
 *     &lt;enumeration value="teal"/>
 *     &lt;enumeration value="white"/>
 *     &lt;enumeration value="yellow"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "standard_color_type")
@XmlEnum
public enum StandardColorType {

    @XmlEnumValue("aqua")
    AQUA("aqua"),
    @XmlEnumValue("black")
    BLACK("black"),
    @XmlEnumValue("blue")
    BLUE("blue"),
    @XmlEnumValue("fuchsia")
    FUCHSIA("fuchsia"),
    @XmlEnumValue("gray")
    GRAY("gray"),
    @XmlEnumValue("green")
    GREEN("green"),
    @XmlEnumValue("lime")
    LIME("lime"),
    @XmlEnumValue("maroon")
    MAROON("maroon"),
    @XmlEnumValue("navy")
    NAVY("navy"),
    @XmlEnumValue("olive")
    OLIVE("olive"),
    @XmlEnumValue("purple")
    PURPLE("purple"),
    @XmlEnumValue("red")
    RED("red"),
    @XmlEnumValue("silver")
    SILVER("silver"),
    @XmlEnumValue("teal")
    TEAL("teal"),
    @XmlEnumValue("white")
    WHITE("white"),
    @XmlEnumValue("yellow")
    YELLOW("yellow");
    private final String value;

    StandardColorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StandardColorType fromValue(String v) {
        for (StandardColorType c: StandardColorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
