//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 12:14:36 AM CST 
//


package org.oasis.xmile.v1_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for standard_method_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="standard_method_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="euler"/>
 *     &lt;enumeration value="rk2"/>
 *     &lt;enumeration value="rk2_auto"/>
 *     &lt;enumeration value="rk4"/>
 *     &lt;enumeration value="rk4_auto"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "standard_method_type")
@XmlEnum
public enum StandardMethodType {

    @XmlEnumValue("euler")
    EULER("euler"),
    @XmlEnumValue("rk2")
    RK_2("rk2"),
    @XmlEnumValue("rk2_auto")
    RK_2_AUTO("rk2_auto"),
    @XmlEnumValue("rk4")
    RK_4("rk4"),
    @XmlEnumValue("rk4_auto")
    RK_4_AUTO("rk4_auto");
    private final String value;

    StandardMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StandardMethodType fromValue(String v) {
        for (StandardMethodType c: StandardMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
